weather_api_key: 708e47ba1f004e70a33171436231005
google_client_id: 492497800586-cilkc5lmileb6841h5clbdb80io4kjqo.apps.googleusercontent.com
google_client_secret: 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
app_host: 'http://localhost:3000'
